apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-secrets
spec:
  selector:
    matchLabels:
      app: test-secrets
  replicas: 1
  template:
    metadata:
      labels:
        app: test-secrets
    spec:
      containers:
        - name: test-secrets
          image: __FULL_IMAGE_GITHUB_SHA__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080