apiVersion: v1
kind: Service
metadata:
  name: testsecrets-service
  namespace: default
spec:
  selector:
    app: testsecrets
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort