# This is a basic workflow that is manually triggered

name: Create service in dev

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  # Inputs the workflow accepts.

env:
  PROJECT_DEV: test-kubernetes-dev
  GAR_LOCATION: europe-north1
  GKE_CLUSTER: autopilot-cluster-2
  GKE_ZONE: europe-north1-a
  IMAGE: testsecrets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_DEV_SA_KEY }}
          project_id: premium-bloom-369416
          install_components: "gke-gcloud-auth-plugin,kustomize,kubectl"

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl apply -f service.yaml
          kubectl get services -o wide